revising travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,13 +2,38 @@ language: haskell
 ghc:
   - 7.8
 sudo: required
+
 before_install:
-  - travis_retry sudo apt-get install happy  
+  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+  - travis_retry sudo apt-get update
+  - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER happy
+  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+
 install:
-  - cabal install hlint
+  - cabal-1.20 update
+  - travis_retry sudo apt-get -q -y install hlint || cabal-1.20 install hlint
+  - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks
+
 script:
   - hlint . --ignore="Parse error"
-  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test --show-details=always
+  - cabal-1.20 configure --enable-tests --enable-benchmarks --enable-library-coverage -v2
+  - cabal-1.20 build
+  - |
+    if [ $GHCVER = "7.8.3" ]; then
+      cabal-1.20 test --show-details=always
+    else
+      dist/build/run-cabal-test/run-cabal-test --cabal-name=cabal-1.20 --show-details=always
+    fi
+  - cabal-1.20 check
+  - cabal-1.20 sdist
+  - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
+    (cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+      cabal-1.20 install "$SRC_TGZ";
+    else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+    fi)
+
 after_script:
-  - cabal install codecov-haskell
-  - codecov-haskell test-json-litobj
+  - dist/build/codecov-haskell/codecov-haskell test-all --exclude-dir=test --display-report --print-response
